### ISSUE TITLE
typo in Sigmoid function range

### ISSUE THREAD

**Issue by AlexandrParkhomenko** [shervinea/cheatsheet-translation#215]
## typo
[https://stanford.edu/~shervine/teaching/cs-229/cheatsheet-supervised-learning](https://stanford.edu/~shervine/teaching/cs-229/cheatsheet-supervised-learning)
g(z)=1+e−z1​∈ **]0,1[​**

## need:
[0, 1]

**Comment by shervinea** [comment]
Thanks for your message and your interest @AlexandrParkhomenko.

This notation follows the [ISO 31-11 convention on sets](https://en.wikipedia.org/wiki/ISO_31-11#Sets). Here, `]0,1[` denotes the interval in `R` from 0 to 1, bounds excluded. The exclusion of bounds is intentional since the function never outputs 0 nor 1.

**Comment by AlexandrParkhomenko** [comment]
I did not know. Thanks for a quick and complete answer.
